### ISSUE TITLE
How do i get this to work on iOS 9 (ionic project)?

### ISSUE THREAD

**Issue by degamer106** [EddyVerbruggen/iOSWebViewColor-PhoneGap-Plugin#10]
I'm trying to change the background color of the HTML select element from the default dark gray on iOS 9 to white. I stumbled across this Phonegap/Cordova plugin: https://github.com/EddyVerbruggen/iOSWebViewColor-PhoneGap-Plugin but I'm not having much luck making it work. Any one else able to get this working on iOS 9?

I tried the sample code in my Ionic project, but there's no effect.

window.plugins.webviewcolor.change('#FFFFFF')

Edit: Here's what I've tried:

- Modifying theWebView.backgroundColor on line 107 in MainViewController.m
- Modifying the MainViewController.xib file and unchecking Opaque.
- Modifying the Objective-C code of the Cordova plugin to force [UIColor whiteColor]

Nothing works.

**Comment by degamer106** [comment]
bump

**Comment by EddyVerbruggen** [comment]
I just created a new project with the Cordova CLI, added the plugin, then added this code:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi" />
        <link rel="stylesheet" type="text/css" href="css/index.css" />
        <title>Hello World</title>
    </head>
    <body>
        <div class="app">
            <h1>Apache Cordova</h1>
            <div id="deviceready" class="blink">
                <p class="event listening">Connecting to Device</p>
                <p class="event received">Device is Ready</p>
                <button onclick="window.plugins.webviewcolor.change('#FF0000')">change to #FF0000</button>
                <button onclick="window.plugins.webviewcolor.change('#00FF00', function(){alert('color was changed!')})">change to #00FF00</button>
                <input type="text" name="test"/>
                <select>
                <option>a</option>
                <option>b</option>
                </select>
            </div>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
        <script type="text/javascript">
            app.initialize();
        </script>
    </body>
</html>
```

This is the result:

![img_5403](https://cloud.githubusercontent.com/assets/1426370/10157014/a2007bc2-6686-11e5-9b0d-b5b16692e993.PNG)

![img_5402](https://cloud.githubusercontent.com/assets/1426370/10157015/a2d742f6-6686-11e5-8c9f-41324781d548.PNG)

**Comment by degamer106** [comment]
So in iOS 9, they made the color of the <select> scroller non-transparent then :(
