### ISSUE TITLE
Black background that doesn't change.

### ISSUE THREAD

**Issue by leandroz** [EddyVerbruggen/iOSWebViewColor-PhoneGap-Plugin#8]
Hey! i hope someone had this problem before and knows how to solve it.
I have a background black color in the parts of my app with scroll, i tried changing the background color but without any luck.
![background-backcolor](https://cloud.githubusercontent.com/assets/4624850/6260567/c497876c-b834-11e4-8cd9-9aebd07a407c.png)
The same problem at the top, like this image:
![img_3183](https://cloud.githubusercontent.com/assets/4624850/6260571/daecb0aa-b834-11e4-8b35-bdeff6e92f0e.PNG)

**Comment by trevorblades** [comment]
I'm getting the same problem. I'm trying to set the background color in my deviceready handler like so:

```javascript
function onDeviceReady() {
	window.plugins.webviewcolor.change('#FFFFFF');
};
document.addEventListener('deviceready', onDeviceReady, false);
```

**Comment by EddyVerbruggen** [comment]
Can I check the complete sourcecode somehow? Perhaps by email?

**Comment by leandroz** [comment]
The problem i think is not the background color because when i open the Keyboard the color is changed, is not html problem either. I am making scrollable only the ```main``` html element using:
````
top: 4rem;
background-color: #fff;
position: fixed;
width: 100%;
height: auto;
bottom: 0;
-webkit-overflow-scrolling: touch;
overflow-y: auto;
````

**Comment by leandroz** [comment]
Ok, this is weird, i actually solved the problem removing the background color of the child element of the scrollable element. Inside the main tag was a menu tag with the same background color, i remove it and now all is white as it should.
